version: '3'
services:
  iaww:
    restart: always
    image: iaww/main
    container_name: iaww
    depends_on:
    - iaww-letsencrypt
    ports:
      - 8080:8080
    volumes:
      - "/etc/iaww/db:/app/db"
  iaww-letsencrypt:
    image: linuxserver/swag
    container_name: iaww-letsencrypt
    ports:
      - 80:80
      - 443:443
    volumes:
      - "/vagrant/nginx/default:/config/nginx/site-confs/default"
      - "/etc/letsencrypt:/config"
    environment:
      - EMAIL=pierrealain.keyser@gmail.com
      - URL=pakeyser.ddns.net
      - VALIDATION=http
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=999
      - STAGING=false
    